"""Add role to users

Revision ID: 4a04ba193758
Revises: 659978f5e0e6
Create Date: 2025-06-11 16:33:49.743062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a04ba193758'
down_revision: Union[str, None] = '659978f5e0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('users', sa.Column(
        'role',
        sa.String(),
        nullable=False,
        server_default='user'
    ))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
