"""Add responder model

Revision ID: 659978f5e0e6
Revises: 767e6d4fb013
Create Date: 2025-06-11 14:47:30.784281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '659978f5e0e6'
down_revision: Union[str, None] = '767e6d4fb013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_responders_id'), 'responders', ['id'], unique=False)
    op.add_column('tickets', sa.Column('responder_id', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'tickets', 'responders', ['responder_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('tickets', 'responder_id')
    op.drop_index(op.f('ix_responders_id'), table_name='responders')
    op.drop_table('responders')
    # ### end Alembic commands ###
